name: BuildV8
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  monolith_build:
    name: V8 monolith Build
    runs-on: windows-latest
    steps:
      - name: Set Env
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://storage.googleapis.com/chrome-infra/depot_tools.zip','depot_tools.zip')
          7z x -aoa -oC:\depot_tools depot_tools.zip
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.3
      - name: Build
        run: |
          $Env:PATH = "C:\depot_tools;$Env:PATH"
          $Env:DEPOT_TOOLS_WIN_TOOLCHAIN = 0
          gclient ; mkdir C:\v8 ; cd C:\v8 ; fetch v8 ; cd v8 ; ls
          gn gen out/x64.Release --args='v8_monolithic=true v8_use_external_startup_data=false use_custom_libcxx=false is_component_build=false treat_warnings_as_errors=false symbol_level=0 is_debug=false target_cpu=\"x64\"'
          ninja -C out/x64.Release/ v8_monolith
      - name: Package Library
        run: |
          Get-ChildItem -Path C:\v8\v8\out\x64.Release -Filter *.pdb -Recurse | Remove-Item -Force
          7z a v8_monolith_x64_release.7z C:\v8\v8\include C:\v8\v8\out\x64.Release\obj\v8_monolith.lib
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v8
          body: 'Publish to GitHub Release'
          files: v8_monolith_x64_release.7z
  
  V8_dll_build:
    name: V8 DLL Build
    runs-on: windows-latest
    steps:
      - name: Set Env
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://storage.googleapis.com/chrome-infra/depot_tools.zip','depot_tools.zip')
          7z x -aoa -oC:\depot_tools depot_tools.zip
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.3
      - name: Build
        run: |
          $Env:PATH = "C:\depot_tools;$Env:PATH"
          $Env:DEPOT_TOOLS_WIN_TOOLCHAIN = 0
          gclient ; mkdir C:\v8 ; cd C:\v8 ; fetch v8 ; cd v8 ; ls
          gn gen out/x64.Release --args='is_component_build=false v8_symbol_level=0 is_debug=false target_cpu=\"x64\"'
          ninja -C out/x64.Release/ v8
      - name: Package Library
        run: |
          rm -r -Force C:\v8\v8\out\x64.Release\obj
          rm -r -Force C:\v8\v8\out\x64.Release\gen
          Get-ChildItem -Path C:\v8\v8\out\x64.Release -Filter *.pdb -Recurse | Remove-Item -Force
          7z a v8_dll_x64_release.7z C:\v8\v8\out\x64.Release
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v8
          body: 'Publish to GitHub Release'
          files: v8_dll_x64_release.7z

  V8_dll_custom_build:
    name: V8 DLL Custom Build
    runs-on: windows-latest
    steps:
      - name: Set Env
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://storage.googleapis.com/chrome-infra/depot_tools.zip','depot_tools.zip')
          7z x -aoa -oC:\depot_tools depot_tools.zip
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.3
      - name: Build No Wasm
        run: |
          $Env:PATH = "C:\depot_tools;$Env:PATH"
          $Env:DEPOT_TOOLS_WIN_TOOLCHAIN = 0
          gclient ; mkdir C:\v8 ; cd C:\v8 ; fetch v8 ; cd v8 ; ls
          gn gen out/x64.Release --args='symbol_level=0 is_component_build=false v8_enable_webassembly=false is_debug=false target_cpu=\"x64\"'
          ninja -C out/x64.Release/ v8
      - name: Package Library
        run: |
          rm -r -Force C:\v8\v8\out\x64.Release\obj
          rm -r -Force C:\v8\v8\out\x64.Release\gen
          Get-ChildItem -Path C:\v8\v8\out\x64.Release -Filter *.pdb -Recurse | Remove-Item -Force
          7z a v8_custom_dll_x64_release.7z C:\v8\v8\out\x64.Release
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v8
          body: 'Publish to GitHub Release'
          files: v8_custom_dll_x64_release.7z

  V8_dll_mini_build:
    name: V8 DLL Custom Build
    runs-on: windows-latest
    steps:
      - name: Set Env
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://storage.googleapis.com/chrome-infra/depot_tools.zip','depot_tools.zip')
          7z x -aoa -oC:\depot_tools depot_tools.zip
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.3
      - name: Build No Wasm
        run: |
          $Env:PATH = "C:\depot_tools;$Env:PATH"
          $Env:DEPOT_TOOLS_WIN_TOOLCHAIN = 0
          gclient ; mkdir C:\v8 ; cd C:\v8 ; fetch v8 ; cd v8 ; ls
          gn gen out/x64.Release --args='symbol_level=0 is_component_build=false v8_enable_webassembly=false v8_enable_i18n_support=false is_debug=false target_cpu=\"x64\"'
          ninja -C out/x64.Release/ v8
      - name: Package Library
        run: |
          rm -r -Force C:\v8\v8\out\x64.Release\obj
          rm -r -Force C:\v8\v8\out\x64.Release\gen
          Get-ChildItem -Path C:\v8\v8\out\x64.Release -Filter *.pdb -Recurse | Remove-Item -Force
          7z a v8_mini_dll_x64_release.7z C:\v8\v8\out\x64.Release
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v8
          body: 'Publish to GitHub Release'
          files: v8_mini_dll_x64_release.7z