name: Test
on:
  push:
    branches: [ "Test" ]
  pull_request:
    branches: [ "Test" ]
jobs:
  build:
    name: Test
    runs-on: windows-2019
    steps:
      - name: Set Env
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://storage.googleapis.com/chrome-infra/depot_tools.zip','depot_tools.zip')
          7z x -aoa -oC:\depot_tools depot_tools.zip
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.2
      - name: Build
        run: |
          $Env:PATH = "C:\depot_tools;$Env:PATH"
          $Env:DEPOT_TOOLS_WIN_TOOLCHAIN = 0
          gclient
          mkdir C:\v8
          cd C:\v8
          fetch v8
          cd v8
          gn args out/foo --list
          # python ./tools/dev/gm.py x64.release
          # gn gen "--args=is_clang=true is_component_build=false v8_static_library=true use_custom_libcxx=false target_cpu=\"x64\"" out.gn/x64.Release
          # ninja -C out.gn/x64.Release/
          # ls
          # cd ..
          # ls
      # - name: Package Library
      #   run: |
      #     rm -r -Force C:\v8\v8\out.gn\x64.Release\obj
      #     rm -r -Force C:\v8\v8\out.gn\x64.Release\gen
      #     7z a v8_x64_release.7z C:\v8\v8\out.gn\x64.Release\
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: v8_x64_release
      #     path: v8_x64_release.7z
          
